apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-istanbul-

resources:
- ../../base

components:
  - ../../variants/prod
  - ../../variants/istanbul

patchesStrategicMerge:
- deployment.yaml
- version.yaml
- replicas.yaml
- settings.yaml
